### ISSUE TITLE
Стейт у цьому сервісі не потрібен

### ISSUE THREAD

**Issue by shkiper** [cleargoal/panda-monitor#3]
https://github.com/cleargoal/panda-monitor/blob/e2b9ba42b690c598291b87edbe086da8408caa4f/app/Services/SubscribeService.php#L17
Трішки не зрозуміло, навіщо в цьому сервісі зберігати якийсь стейт, якщо ти ці данні можеш прокинути в протектед методи. Бачу що є сетап цих данних, а в іншому методі читання, але навіщо такі маніпуляції заради прокидання данних із одного методу в інший?

**Comment by cleargoal** [comment]
Моя особиста думка, що члени класа це зручнішк, ніж прокидання між методами. Але як вже коменували в чаті - ще дехто теж радять прокидувати, то ж позбувся тих змінних.

**Comment by shkiper** [comment]
це дуже погана практика
ти ж не збираєшся цей стейт десь використовувати в іншому місці, за межами сервісу? Виглядає що ні
Треба ще якось ці данні очищати, щоб попередити неправильні данні. 
Але для передачі данних між двома методами, заводити стейт в сервісі - дуже погана ідея. Взагалі, в сервісі щось зберігати погана ідея, сервіси мають бути без стейту

**Comment by cleargoal** [comment]
Зрозумів. Дякую!
